### ISSUE TITLE
Logfiles of multi-configuration projects are not compressed

### ISSUE THREAD

**Issue by buesse** [daniel-beck/compress-buildlog-plugin#1]
Normal Logfiles 
**$WORKSPACE/../build/\*/\*.log** are compressed as in normal projects, but in Multi-configuration projects they only consist of a couple of lines, describing which axis jobs where triggered.

In Multi-configuration projects the relevat Logfiles are in the configurations directory, separated via axis 
**$WORKSPACE/../configurations/\*\*/builds/\*/log**
\*\* here is a placeholder for multiple (depending on the count of axis) sub-directories of the form
**axis-AXIS_NAME/AXIS_VALUE** 

These Logfiles should be compressed too.

**Comment by uweschaefer** [comment]
for maven projects, i did the necessary change. But now, this plugin is dependent on maven and so i hesitate to create a pull req. would it be reasonable to have a different flavour of this plugin for maven projects?

**Comment by buesse** [comment]
We are using a workaround and compress the logfiles for out ant based projects nightly via a cron job.

**Comment by uweschaefer** [comment]
A separate process is not really an option for us. Would you want me to create a pull req, or start a different plugin variant?

**Comment by daniel-beck** [comment]
@uweschaefer @buesse This plugin has been forked into the @jenkinsci organization, all future development will happen there. Please file a bug against the plugin as described [here](https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue). I'll disable this issue tracker now.
